steps:

# build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/python-server-automated:$REVISION_ID', '.']
  id: 'build'

# push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/python-server-automated:$REVISION_ID']
  id: 'push'

# deploy
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--image-url', 'gcr.io/$PROJECT_ID/python-server-automated:$REVISION_ID']
